version: '3'
services:

  celeryworker:
    env_file: environment.secret
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -E -A tasks worker --loglevel=info --broker=redis://redis:6379/2
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - backend

  celerybeat:
    env_file: environment.secret
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks beat --broker=redis://redis:6379/2
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - backend

  celeryflower:
    env_file: environment.secret
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks flower --address=0.0.0.0 --port=5555 --broker=redis://redis:6379/2
    ports:
      - 5555:5555
    networks:
      - backend
    depends_on:
      - redis

  redis:
    image: redis
    hostname: redis
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
